name: Caller Workflow
on: [workflow_dispatch]
jobs:
  general-ravnica:
    uses: ./.github/workflows/ravnica.yml
    with:
      guild: Izzet
    secrets:
      guildpact: Niv-Mizzet
  post-dragons-maze:
    uses: ./.github/workflows/ravnica.yml
    with:
      environment: PostDragonsMaze
      guild: Dimir
    secrets: inherit
